version: '3'
services:
  apache2:
    image: mysql/mysql-server:5.7
    container_name: apache2
    volumes:
      - ./magento2:/var/www/html
      - ./web_server/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    ports:
      - "80:80"
    links:
      - database_server
  database_server:
    build:
      context: ./database_server/
      args:
        - mysql_password=db_pass
        - mysql_database=magento_dev
    container_name: mysql
    volumes:
      - ./database_server/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
      - ./database_server/mysql.sh:/etc/mysql.sh
    ports:
      - "3306:3306"
